begin tran
alter table cliente_dados_meio_pagto_historico alter column valor_dado VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table rotina_rodape_linha alter column idioma VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table rotina_rodape_linha alter column nm_campo_layout VARCHAR (100) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table rotina_rodape_linha alter column ds_campo VARCHAR (100) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table rotina_rodape_linha alter column ds_conteudo VARCHAR (100) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table rotina_rodape_linha alter column ds_conteudo_arquivo VARCHAR (1000) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table rotina_rodape_linha alter column codigo_tipo_falha VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table rotina_rodape_linha alter column ds_erro_arquivo VARCHAR (500) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table log_processamento alter column certificado_legado VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table log_processamento alter column nm_arquivo VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table log_processamento alter column nm_interface VARCHAR (100) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table log_processamento_detalhe alter column ds_detalhe VARCHAR (Max) collate  SQL_Latin1_General_CP1_CI_AS null;

/****** Object:  Index [status_cotacao_PK]    Script Date: 01/10/2018 14:37:04 ******/
ALTER TABLE [dbo].[status_cotacao] DROP CONSTRAINT [status_cotacao_PK]
GO


alter table status_cotacao alter column idioma VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table status_cotacao alter column nm_status_cotacao VARCHAR (50) collate  SQL_Latin1_General_CP1_CI_AS not  null;

/****** Object:  Index [status_cotacao_PK]    Script Date: 01/10/2018 14:36:23 ******/
ALTER TABLE [dbo].[status_cotacao] ADD  CONSTRAINT [status_cotacao_PK] PRIMARY KEY NONCLUSTERED 
(
	[id_status_cotacao] ASC,
	[idioma] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


alter table log_sintetico alter column id_fluxo VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table log_sintetico alter column nm_fluxo VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table log_sintetico alter column ds_erro_execucao VARCHAR (Max) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table log_sintetico alter column idioma VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS not  null;

/****** Object:  Index [status_documentacao_PK]    Script Date: 01/10/2018 14:38:00 ******/
ALTER TABLE [dbo].[status_documentacao] DROP CONSTRAINT [status_documentacao_PK]
GO

alter table status_documentacao alter column idioma VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table status_documentacao alter column nm_sta_doc VARCHAR (50) collate  SQL_Latin1_General_CP1_CI_AS not  null;

/****** Object:  Index [status_documentacao_PK]    Script Date: 01/10/2018 14:38:23 ******/
ALTER TABLE [dbo].[status_documentacao] ADD  CONSTRAINT [status_documentacao_PK] PRIMARY KEY NONCLUSTERED 
(
	[id_sta_doc] ASC,
	[idioma] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

alter table log_tabela alter column nm_tabela NVARCHAR (256) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table log_tabela alter column acao CHAR (6) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table log_tabela alter column valor_log VARCHAR (8000) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table controle_alt_cliente_produto alter column nr_proposta VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table controle_alt_cliente_produto alter column id_fluxo_1 VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table controle_alt_cliente_produto alter column id_fluxo_2 VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table controle_alt_cliente_produto alter column id_fluxo_3 VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table controle_alt_cliente_produto alter column id_fluxo_4 VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table controle_alt_cliente_produto alter column id_fluxo_5 VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table status_fatura alter column idioma VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table status_fatura alter column nm_status_fatura VARCHAR (50) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table controle_alt_pagamento alter column nr_proposta VARCHAR (12) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table controle_alt_pagamento alter column mes_ano_ref VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table controle_alt_pagamento alter column id_fluxo_1 VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table controle_alt_pagamento alter column id_fluxo_2 VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table controle_alt_pagamento alter column id_fluxo_3 VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table controle_alt_pagamento alter column id_fluxo_4 VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table controle_alt_pagamento alter column id_fluxo_5 VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table status_pagamento alter column idioma VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table status_pagamento alter column nm_status_pagto VARCHAR (50) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table motivo_contato_cliente alter column ds_mot VARCHAR (50) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table motivo_contato_cliente alter column idioma VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table status_pericia alter column idioma VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table status_pericia alter column nm_st_pericia VARCHAR (50) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table motivo_rejeicao alter column idioma VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table motivo_rejeicao alter column ds_mot_rej VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table motivo_rejeicao alter column id_mot_rej_legado VARCHAR (100) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table motivo_rejeicao alter column auxiliar VARCHAR (100) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table status_processo alter column idioma VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table status_processo alter column nm_status_processo VARCHAR (50) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table pagamento alter column nr_proposta VARCHAR (12) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table pagamento alter column nr_endosso_prod_emp VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table pagamento alter column mes_ano_ref VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table pagamento alter column nm_tp_meio_pagto VARCHAR (50) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table pagamento alter column nm_meio_pagto VARCHAR (50) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table pagamento alter column cd_autorizacao VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table pagamento alter column idioma VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table pagamento alter column url_recibo VARCHAR (500) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table pagamento alter column nr_ordem_pagto VARCHAR (100) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table pagamento alter column ds_auxiliar VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table pagamento alter column serie VARCHAR (Max) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table correspondencia alter column id_processo VARCHAR (15) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table correspondencia alter column nm_arquivo VARCHAR (100) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table correspondencia alter column codigo_envio VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table correspondencia alter column idioma VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table correspondencia alter column assunto VARCHAR (50) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table correspondencia alter column conteudo VARCHAR (Max) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table correspondencia alter column nr_proposta VARCHAR (12) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table correspondencia alter column nr_endosso_prod_emp VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table correspondencia alter column email VARCHAR (120) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table correspondencia alter column obj_envio VARCHAR (Max) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table correspondencia alter column obj_retorno VARCHAR (Max) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table correspondencia alter column cod_retorno VARCHAR (5) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table correspondencia alter column id_tp_endosso_calc_prod VARCHAR (Max) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table correspondencia alter column id_endosso_calc_prod VARCHAR (Max) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table status_produto_cliente_gproxslite alter column idioma VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table status_produto_cliente_gproxslite alter column nm_status_proposta VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table status_produto_cliente_gproxslite alter column nm_status_proposta_gproxslite VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table pagamento_duplicado alter column nm_tp_meio_pagto VARCHAR (17) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table pagamento_duplicado alter column nm_meio_pagto VARCHAR (16) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table pagamento_duplicado alter column dt_credito_cliente VARCHAR (4) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table pagamento_duplicado alter column dt_debito_empresa VARCHAR (4) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table pagamento_duplicado alter column dt_credito_empresa VARCHAR (4) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table pagamento_duplicado alter column cd_autorizacao VARCHAR (4) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table pagamento_duplicado alter column id_login VARCHAR (36) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table pagamento_duplicado alter column id_mot_est VARCHAR (4) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table pagamento_duplicado alter column vl_multa VARCHAR (4) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table pagamento_duplicado alter column vl_juros VARCHAR (4) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table pagamento_duplicado alter column idioma VARCHAR (5) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table pagamento_duplicado alter column url_recibo VARCHAR (4) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table pagamento_duplicado alter column vl_custo_cobranca VARCHAR (4) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table pagamento_duplicado alter column dt_custo_cobranca VARCHAR (4) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table pagamento_duplicado alter column dt_movimento VARCHAR (4) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table pagamento_duplicado alter column dt_faturado VARCHAR (4) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table pagamento_duplicado alter column nr_periodo_1a_parcela VARCHAR (4) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table pagamento_duplicado alter column id_periodo_1a_parcela VARCHAR (4) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table pagamento_duplicado alter column fl_avista VARCHAR (4) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table pagamento_duplicado alter column nr_endosso_origem VARCHAR (4) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table pagamento_duplicado alter column dt_selecao VARCHAR (4) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table pagamento_duplicado alter column id_fluxo_instancia_selecao_cobranca VARCHAR (4) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table pagamento_duplicado alter column id_range VARCHAR (4) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table pagamento_duplicado alter column serie VARCHAR (22) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table pagamento_duplicado alter column id_status_sorteado VARCHAR (4) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table pagamento_duplicado alter column id_pagto_anterior VARCHAR (4) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table correspondenciaXdestinatario alter column id_processo VARCHAR (15) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table status_proposta alter column idioma VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table status_proposta alter column nm_status_proposta VARCHAR (50) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table pagamento_fatura alter column nr_endosso_prod_emp VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table pagamento_fatura alter column nr_fat_cliente VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table pagamento_fatura alter column idioma_mot_cancel_fat VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table pagamento_fatura alter column idioma_status_fatura VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table pagamento_fatura alter column nr_transacao VARCHAR (100) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table corretor_cotacao alter column nr_cotacao VARCHAR (12) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table status_reserva_processo_beneficio alter column idioma VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table status_reserva_processo_beneficio alter column nm_st_reserva VARCHAR (50) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table pagamento_fatura_comissao alter column nr_endosso_prod_emp VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table pagamento_fatura_comissao alter column nr_orden_pagto VARCHAR (15) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table pagamento_fatura_comissao alter column nr_orden_anula VARCHAR (15) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table cotacao_cliente alter column nr_cotacao VARCHAR (12) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table cotacao_cliente alter column idioma VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table cotacao_cliente alter column endosso_apolice VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table cotacao_cliente alter column nr_endosso_prod_emp VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table cotacao_cliente_dados_calculo alter column nr_cotacao VARCHAR (12) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table pagamento_faturaXpagamento alter column nr_proposta VARCHAR (12) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table pagamento_faturaXpagamento alter column nr_endosso_prod_emp VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table cotacao_cliente_dados_calculo_cobertura alter column nr_cotacao VARCHAR (12) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table cotacao_cliente_dados_calculo_cobertura alter column idioma VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table pagamento_historico_processamento alter column nr_proposta VARCHAR (12) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table pagamento_historico_processamento alter column nr_endosso_prod_emp VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table pagamento_historico_processamento alter column nm_interface VARCHAR (100) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table cotacao_cliente_dados_impostos alter column nr_cotacao VARCHAR (12) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table pagamento_parcial alter column nr_proposta VARCHAR (12) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table pagamento_parcial alter column nr_endosso_prod_emp VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table pagamento_parcial alter column idioma VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table pagamento_parcial alter column ds_auxiliar VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table cotacao_clienteXfranquia alter column nr_cotacao VARCHAR (12) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table cotacao_clienteXfranquia alter column idioma VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table pagamento_parcial_historico_processamento alter column nr_proposta VARCHAR (12) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table pagamento_parcial_historico_processamento alter column nr_endosso_prod_emp VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table pagamento_parcial_historico_processamento alter column nm_interface VARCHAR (100) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table cotacao_clienteXparcelas alter column nr_cotacao VARCHAR (12) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table pagina alter column nome VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table cotacao_clienteXremuneracao_corretor alter column nr_cotacao VARCHAR (12) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table prestador_servicoXprocesso_beneficioXreservaXcobertura_tipo_produto alter column id_processo VARCHAR (15) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table prestador_servicoXprocesso_beneficioXreservaXcobertura_tipo_produto alter column idioma VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table cotacao_clienteXvalores_beneficio alter column nr_cotacao VARCHAR (12) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table prestador_servicoXprocesso_beneficioXreservaXsubcobertura_tipo_produto alter column id_processo VARCHAR (15) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table prestador_servicoXprocesso_beneficioXreservaXsubcobertura_tipo_produto alter column idioma VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table dados_beneficiarios alter column nr_proposta VARCHAR (12) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table dados_beneficiarios alter column nr_endosso_prod_emp VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table dados_beneficiarios alter column idioma VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table dados_beneficiarios alter column valor_dado VARCHAR (500) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table processo_beneficio alter column id_processo VARCHAR (15) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table processo_beneficio alter column id_processo_fornec VARCHAR (100) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table processo_beneficio alter column id_processo_corretor VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table processo_beneficio alter column id_processo_ref VARCHAR (15) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table processo_beneficio alter column nm_solicitante VARCHAR (50) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table processo_beneficio alter column tel_solicitante VARCHAR (14) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table processo_beneficio alter column email_solicitante VARCHAR (100) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table processo_beneficio alter column obs VARCHAR (5000) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table processo_beneficio alter column idioma VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table processo_beneficio alter column nr_proposta VARCHAR (12) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table processo_beneficio alter column idioma_mot_enc VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table processo_beneficio alter column obs_sindicancia_especial VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table processo_beneficio alter column nr_endosso_prod_emp VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table dados_cliente alter column valor_dado_cli VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table processo_beneficio_motivo alter column id_processo VARCHAR (15) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table processo_beneficio_motivo alter column resumo_motivo VARCHAR (300) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table processo_beneficio_motivo alter column motivo_reabertura VARCHAR (300) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table processo_beneficio_motivo alter column idioma VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table dados_contato alter column idioma VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table dados_contato alter column valor_dado_contato VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table processo_beneficio_observacao alter column id_processo VARCHAR (15) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table processo_beneficio_observacao alter column obs VARCHAR (Max) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table dados_declaracao_saude alter column nr_proposta VARCHAR (12) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table dados_declaracao_saude alter column nr_endosso_prod_emp VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table dados_declaracao_saude alter column ds_comentario VARCHAR (100) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table processo_beneficio_pagamento alter column id_processo VARCHAR (15) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table processo_beneficio_pagamento alter column id_processo_cob VARCHAR (15) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table processo_beneficio_pagamento alter column idioma_cob VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table processo_beneficio_pagamento alter column id_processo_subcob VARCHAR (15) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table processo_beneficio_pagamento alter column idioma_subcob VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table processo_beneficio_pagamento alter column id_processo_beneficiario_cob VARCHAR (15) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table processo_beneficio_pagamento alter column idioma_beneficiario_cob VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table processo_beneficio_pagamento alter column id_processo_beneficiario_subcob VARCHAR (15) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table processo_beneficio_pagamento alter column idioma_beneficiario_subcob VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table processo_beneficio_pagamento alter column idioma_mot_enc VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table dados_declaracao_saudeXtipo_participante alter column nr_proposta VARCHAR (12) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table dados_declaracao_saudeXtipo_participante alter column nr_endosso_prod_emp VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table processo_beneficio_pagamento_item alter column id_processo VARCHAR (15) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table processo_beneficio_pagamento_item alter column nr_doc_pagto VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table processo_beneficio_pagamento_item alter column id_processo_cob VARCHAR (15) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table processo_beneficio_pagamento_item alter column idioma_cob VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table processo_beneficio_pagamento_item alter column id_processo_beneficiario_cob VARCHAR (15) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table processo_beneficio_pagamento_item alter column idioma_beneficiario_cob VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table dados_entrega alter column id_processo VARCHAR (15) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table dados_entrega alter column endereco VARCHAR (100) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table dados_entrega alter column numero VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table dados_entrega alter column complemento VARCHAR (100) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table dados_entrega alter column cidade VARCHAR (50) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table dados_entrega alter column estado VARCHAR (50) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table dados_entrega alter column pais VARCHAR (50) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table dados_entrega alter column cep CHAR (10) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table processo_beneficio_pagamento_item_parcelas alter column id_processo VARCHAR (15) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table processo_beneficio_pagamento_item_parcelas alter column idioma VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table processo_beneficio_pagamento_item_parcelas alter column nr_ordem_pagto VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table dados_meio_pagamento alter column id_processo VARCHAR (15) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table dados_meio_pagamento alter column idioma VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table dados_meio_pagamento alter column vl_dado_campo_meio_pagto VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table processo_beneficio_pagamentoXcampos_meio_pagamento alter column id_processo VARCHAR (15) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table processo_beneficio_pagamentoXcampos_meio_pagamento alter column idioma VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table processo_beneficio_pagamentoXcampos_meio_pagamento alter column pro_id_processo VARCHAR (15) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table processo_beneficio_pagamentoXcampos_meio_pagamento alter column valor VARCHAR (100) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table tb_selecao_cobranca alter column nr_proposta VARCHAR (12) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table tb_selecao_cobranca alter column mes_ano_ref VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table tb_selecao_cobranca alter column ds_erro VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table tb_selecao_cobranca alter column obj_envio VARCHAR (Max) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table tb_selecao_cobranca alter column obj_retorno VARCHAR (Max) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table dados_motivo_contato alter column observacao VARCHAR (700) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table dados_motivo_contato alter column fita VARCHAR (50) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table dados_motivo_contato alter column localizador VARCHAR (100) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table dados_motivo_contato alter column nr_protocolo VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table dados_motivo_contato alter column nm_img_documento VARCHAR (100) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table dados_motivo_contato alter column nm_arq_gravacao VARCHAR (100) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table dados_motivo_contato alter column idioma_forma_contato VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table dados_motivo_contato alter column nr_endosso_prod_emp VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table dados_motivo_contato alter column nr_proposta VARCHAR (12) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table processo_beneficioXacesso_beneficioXcobertura_tipo_produto alter column id_processo VARCHAR (15) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table processo_beneficioXacesso_beneficioXcobertura_tipo_produto alter column idioma VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table dados_motivo_contato_adicional alter column observacao VARCHAR (1000) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table dados_motivo_contato_adicional alter column nm_img_documento VARCHAR (100) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table dados_motivo_contato_adicional alter column nm_arq_gravacao VARCHAR (100) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table dados_motivo_contato_adicional alter column fita VARCHAR (50) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table dados_motivo_contato_adicional alter column localizador VARCHAR (100) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table dados_motivo_contato_adicional alter column idioma_forma_contato VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table processo_beneficioXacesso_beneficioXsubcobertura_tipo_produto alter column id_processo VARCHAR (15) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table processo_beneficioXacesso_beneficioXsubcobertura_tipo_produto alter column idioma VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table dados_produto alter column nr_proposta VARCHAR (12) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table dados_produto alter column nr_endosso_prod_emp VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table dados_produto alter column vl_dado_prod VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table dados_produto alter column vl_ref_dado_prod VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table processo_beneficioXbem_adquirido alter column id_processo VARCHAR (15) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table dados_produto_cotacao alter column nr_cotacao VARCHAR (12) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table dados_produto_cotacao alter column vl_dado_produto VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table dados_produto_cotacao alter column vl_ref_dado_prod VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table processo_beneficioXdados_produto alter column id_processo VARCHAR (15) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table processo_beneficioXdados_produto alter column nr_proposta VARCHAR (12) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table processo_beneficioXdados_produto alter column nr_endosso_prod_emp VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table dados_sinistro alter column idioma VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table dados_sinistro alter column id_processo VARCHAR (15) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table dados_sinistro alter column vl_dado_sinistro VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table processo_beneficioXreservaXcobertura_tipo_produto alter column id_processo VARCHAR (15) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table processo_beneficioXreservaXcobertura_tipo_produto alter column idioma VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table destinatario_remetente alter column email VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table destinatario_remetente alter column cep VARCHAR (9) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table destinatario_remetente alter column endereco VARCHAR (200) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table destinatario_remetente alter column numero VARCHAR (100) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table destinatario_remetente alter column complemento VARCHAR (100) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table destinatario_remetente alter column nome VARCHAR (100) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table destinatario_remetente alter column telefone VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table destinatario_remetente alter column id_processo VARCHAR (15) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table processo_beneficioXreservaXcobertura_tipo_produto_historico alter column idioma VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table processo_beneficioXreservaXcobertura_tipo_produto_historico alter column id_processo VARCHAR (15) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table documentacao alter column id_processo VARCHAR (15) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table documentacao alter column cod_arquivo VARCHAR (30) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table documentacao alter column nm_imagem_doc VARCHAR (500) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table documentacao alter column observacao VARCHAR (300) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table documentacao alter column idioma VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table processo_beneficioXreservaXsubcobertura_tipo_produto alter column id_processo VARCHAR (15) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table processo_beneficioXreservaXsubcobertura_tipo_produto alter column idioma VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table processo_beneficioXreservaXsubcobertura_tipo_produto_historico alter column idioma VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table processo_beneficioXreservaXsubcobertura_tipo_produto_historico alter column id_processo VARCHAR (15) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table etl_controle_job alter column ds_mensagem VARCHAR (Max) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table status_cobranca alter column nm_status_cobranca VARCHAR (50) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table status_cobranca alter column idioma VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table produto_cliente alter column nr_proposta VARCHAR (12) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table produto_cliente alter column nr_endosso_prod_emp VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table produto_cliente alter column txt_clausula_benefic VARCHAR (500) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table produto_cliente alter column nr_apolice VARCHAR (30) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table produto_cliente alter column idioma VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table produto_cliente alter column id_mot_can VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table produto_cliente alter column nr_proposta_forn VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table produto_cliente alter column nr_cotacao VARCHAR (12) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table produto_cliente alter column nm_arquivo VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table produto_cliente alter column endosso_apolice VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table produto_cliente alter column arquivo_certificado VARCHAR (100) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table produto_cliente alter column nm_renovacao VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table produto_cliente alter column ds_obs_endosso VARCHAR (500) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table etl_job alter column nm_job VARCHAR (100) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table etl_venda_canc alter column nr_proposta VARCHAR (12) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table etl_venda_canc alter column nm_fantasia_prod VARCHAR (60) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table etl_venda_canc alter column vl_chave1_cli VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table etl_venda_canc alter column vl_chave2_cli VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table etl_venda_canc alter column vl_chave3_cli VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table etl_venda_canc alter column nr_matricula_agente_venda VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table etl_venda_canc alter column nm_agente_venda VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table etl_venda_canc alter column nm_filial_venda VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table etl_venda_canc alter column nm_filial_cadastro VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table etl_venda_canc alter column nm_login_inclusao VARCHAR (100) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table etl_venda_canc alter column nr_matricula_agente_inclusao VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table etl_venda_canc alter column nm_agente_inclusao VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table etl_venda_canc alter column nr_matricula_agente_cancelamento VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table etl_venda_canc alter column nm_agente_cancelamento VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table produto_cliente_bkp_teste_clientes_duplicados alter column nr_proposta VARCHAR (12) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table produto_cliente_bkp_teste_clientes_duplicados alter column nr_endosso_prod_emp VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table produto_cliente_bkp_teste_clientes_duplicados alter column txt_clausula_benefic VARCHAR (500) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table produto_cliente_bkp_teste_clientes_duplicados alter column nr_apolice VARCHAR (30) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table produto_cliente_bkp_teste_clientes_duplicados alter column idioma VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table produto_cliente_bkp_teste_clientes_duplicados alter column id_mot_can VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table produto_cliente_bkp_teste_clientes_duplicados alter column nr_proposta_forn VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table produto_cliente_bkp_teste_clientes_duplicados alter column nr_cotacao VARCHAR (12) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table produto_cliente_bkp_teste_clientes_duplicados alter column nm_arquivo VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table produto_cliente_bkp_teste_clientes_duplicados alter column endosso_apolice VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table produto_cliente_bkp_teste_clientes_duplicados alter column arquivo_certificado VARCHAR (100) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table produto_cliente_bkp_teste_clientes_duplicados alter column nm_renovacao VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table produto_cliente_bkp_teste_clientes_duplicados alter column ds_obs_endosso VARCHAR (500) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table produto_cliente_coberturaXitem_segurado alter column nr_proposta VARCHAR (12) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table produto_cliente_coberturaXitem_segurado alter column nr_endosso_prod_emp VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table produto_cliente_coberturaXitem_segurado alter column idioma VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table extracao_agenciamento alter column nr_proposta VARCHAR (12) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table extracao_agenciamento alter column nr_cotacao VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table tipo_beneficiario alter column idioma VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table tipo_beneficiario alter column nm_tp_beneficiario VARCHAR (50) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table produto_cliente_dados_calculo alter column nr_proposta VARCHAR (12) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table produto_cliente_dados_calculo alter column nr_endosso_prod_emp VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table tipo_operacao_fechamento alter column idioma VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table tipo_operacao_fechamento alter column ds_tp_op VARCHAR (100) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table fechamento_analitico alter column nm_fantasia_prod VARCHAR (60) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table fechamento_analitico alter column nm_camp VARCHAR (50) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table fechamento_analitico alter column nm_agente VARCHAR (50) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table fechamento_analitico alter column nr_proposta VARCHAR (12) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table fechamento_analitico alter column nr_apolice VARCHAR (30) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table fechamento_analitico alter column nr_proposta_forn VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table fechamento_analitico alter column cpf VARCHAR (14) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table fechamento_analitico alter column nome VARCHAR (100) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table produto_cliente_dados_calculo_cobertura alter column nr_proposta VARCHAR (12) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table produto_cliente_dados_calculo_cobertura alter column nr_endosso_prod_emp VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table produto_cliente_dados_calculo_cobertura alter column idioma VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table fechamento_sintetico alter column mes VARCHAR (2) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table fechamento_sintetico alter column ano VARCHAR (4) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table produto_cliente_dados_imposto alter column nr_proposta VARCHAR (12) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table produto_cliente_dados_imposto alter column nr_endosso_prod_emp VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table forma_confirmacao alter column idioma VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table forma_confirmacao alter column nm_forma_confirmacao VARCHAR (50) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table produto_cliente_dados_meio_pagto alter column nr_proposta VARCHAR (12) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table produto_cliente_dados_meio_pagto alter column nr_endosso_prod_emp VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table produto_cliente_dados_meio_pagto alter column valor_dado VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table versao alter column descricao VARCHAR (1000) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table produto_cliente_dados_meio_pagto_historico alter column nr_proposta VARCHAR (12) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table produto_cliente_dados_meio_pagto_historico alter column nr_endosso_prod_emp VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table produto_cliente_dados_meio_pagto_historico alter column valor_dado VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table vistoria_pericia alter column id_processo VARCHAR (15) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table vistoria_pericia alter column resumo VARCHAR (100) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table vistoria_pericia alter column idioma VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table vistoria_pericia alter column nm_imagem_relatorio VARCHAR (500) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table vistoria_pericia alter column id_processo_cob VARCHAR (15) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table vistoria_pericia alter column idioma_cob VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table vistoria_pericia alter column id_processo_subcob VARCHAR (15) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table vistoria_pericia alter column idioma_subcob VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table produto_clienteXcampanha alter column nr_proposta VARCHAR (12) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table produto_clienteXcampanha alter column nr_endosso_prod_emp VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table produto_clienteXendosso_calculo alter column nr_proposta VARCHAR (12) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table produto_clienteXendosso_calculo alter column nr_endosso_prod_emp VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table produto_clienteXendosso_calculo alter column idioma_endosso_calc_prod VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table produto_clienteXfranquia alter column nr_proposta VARCHAR (12) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table produto_clienteXfranquia alter column nr_endosso_prod_emp VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table produto_clienteXfranquia alter column idioma VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table produto_clienteXrange_numero alter column idioma VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table produto_clienteXrange_numero alter column nr_proposta VARCHAR (12) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table produto_clienteXrange_numero alter column nr_endosso_prod_emp VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table grau_parentesco alter column idioma VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table grau_parentesco alter column nm_grau_par VARCHAR (50) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table produto_clienteXremuneracao_corretor alter column nr_proposta VARCHAR (12) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table produto_clienteXremuneracao_corretor alter column nr_endosso_prod_emp VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table produto_clienteXremuneracao_corretor alter column idioma VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table produto_clienteXremuneracao_corretor alter column cod_autorizacao VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table produto_clienteXremuneracao_corretor alter column ds_auxiliar VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table historico_envio_dados_motivo_contato alter column idioma_forma_envio VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table historico_envio_dados_motivo_contato alter column texto_historico VARCHAR (5000) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table historico_envio_dados_motivo_contato alter column ds_nr_protocolos_envio VARCHAR (1000) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table historico_envio_dados_motivo_contato alter column fax VARCHAR (14) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table historico_envio_dados_motivo_contato alter column e_mail VARCHAR (100) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table historico_envio_dados_motivo_contato alter column e_mail_copia VARCHAR (1000) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table historico_envio_dados_motivo_contato alter column endereco VARCHAR (200) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table historico_envio_dados_motivo_contato alter column numero VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table historico_envio_dados_motivo_contato alter column complemento VARCHAR (100) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table historico_envio_dados_motivo_contato alter column cep VARCHAR (9) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table historico_envio_dados_motivo_contato alter column bairro VARCHAR (100) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table historico_envio_dados_motivo_contato alter column cidade VARCHAR (100) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table historico_envio_dados_motivo_contato alter column estado VARCHAR (100) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table historico_envio_dados_motivo_contato alter column pais VARCHAR (30) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table historico_envio_dados_motivo_contato alter column idioma VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table produto_clienteXremuneracao_corretor_parcial alter column nr_proposta VARCHAR (12) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table produto_clienteXremuneracao_corretor_parcial alter column nr_endosso_prod_emp VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table produto_clienteXremuneracao_corretor_parcial alter column idioma VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table produto_clienteXremuneracao_corretor_parcial alter column cod_autorizacao VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table produto_clienteXremuneracao_corretor_parcial alter column ds_auxiliar VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table produto_clienteXremuneracao_empresa alter column nr_proposta VARCHAR (12) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table produto_clienteXremuneracao_empresa alter column nr_endosso_prod_emp VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table produto_clienteXremuneracao_empresa alter column idioma VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table produto_clienteXremuneracao_empresa alter column cod_autorizacao VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table produto_clienteXremuneracao_empresa alter column ds_auxiliar VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table historico_envio_motivo_contato alter column idioma_forma_envio VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table historico_envio_motivo_contato alter column texto_historico VARCHAR (1000) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table historico_envio_motivo_contato alter column ds_nr_protocolos_envio VARCHAR (1000) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table historico_envio_motivo_contato alter column fax VARCHAR (14) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table historico_envio_motivo_contato alter column e_mail VARCHAR (100) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table historico_envio_motivo_contato alter column e_mail_copia VARCHAR (1000) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table historico_envio_motivo_contato alter column cep VARCHAR (9) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table historico_envio_motivo_contato alter column idioma VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table produto_clienteXremuneracao_empresa_parcial alter column nr_proposta VARCHAR (12) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table produto_clienteXremuneracao_empresa_parcial alter column nr_endosso_prod_emp VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table produto_clienteXremuneracao_empresa_parcial alter column idioma VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table produto_clienteXremuneracao_empresa_parcial alter column cod_autorizacao VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table produto_clienteXremuneracao_empresa_parcial alter column ds_auxiliar VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table historico_repiqueXpagamento alter column nr_proposta VARCHAR (12) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table historico_repiqueXpagamento alter column nr_endosso_prod_emp VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table produto_clienteXvalores_beneficios alter column nr_proposta VARCHAR (12) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table produto_clienteXvalores_beneficios alter column nr_endosso_prod_emp VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table identificador_participante_odonto alter column nr_proposta VARCHAR (12) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table autorizacao_pagamento alter column id_processo VARCHAR (15) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table autorizacao_pagamento alter column nr_proposta VARCHAR (12) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table autorizacao_pagamento alter column nr_endosso_prod_emp VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table autorizacao_pagamento alter column idioma VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table autorizacao_pagamento alter column observacao_motivo_cancelamento VARCHAR (1500) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table autorizacao_pagamento alter column idioma_motivo_pagamento VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table autorizacao_pagamento alter column observacao VARCHAR (1500) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table autorizacao_pagamento alter column nr_documento VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table autorizacao_pagamento alter column nr_ordem_pagto VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table autorizacao_pagamento alter column nm_recibo VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table autorizacao_pagamentoXcampos_meio_pagamento alter column idioma VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table autorizacao_pagamentoXcampos_meio_pagamento alter column valor VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table importacao_generica alter column vl_chave1_cli VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table importacao_generica alter column vl_chave2_cli VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table importacao_generica alter column vl_chave3_cli VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table importacao_generica alter column campos_cliente_ordem_1 VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table importacao_generica alter column campos_cliente_ordem_2 VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table importacao_generica alter column campos_cliente_ordem_3 VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table importacao_generica alter column campos_cliente_ordem_4 VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table importacao_generica alter column campos_cliente_ordem_5 VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table importacao_generica alter column campos_cliente_ordem_6 VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table importacao_generica alter column campos_cliente_ordem_7 VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table importacao_generica alter column campos_cliente_ordem_8 VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table importacao_generica alter column campos_cliente_ordem_9 VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table importacao_generica alter column campos_cliente_ordem_10 VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table importacao_generica alter column campos_cliente_ordem_11 VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table importacao_generica alter column campos_cliente_ordem_12 VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table importacao_generica alter column campos_cliente_ordem_13 VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table importacao_generica alter column campos_cliente_ordem_14 VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table importacao_generica alter column campos_cliente_ordem_15 VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table importacao_generica alter column campos_cliente_ordem_16 VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table importacao_generica alter column campos_cliente_ordem_17 VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table importacao_generica alter column campos_cliente_ordem_18 VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table importacao_generica alter column campos_cliente_ordem_19 VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table importacao_generica alter column campos_cliente_ordem_20 VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table importacao_generica alter column campos_cliente_ordem_21 VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table importacao_generica alter column campos_cliente_ordem_22 VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table importacao_generica alter column campos_cliente_ordem_23 VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table importacao_generica alter column campos_cliente_ordem_24 VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table importacao_generica alter column campos_cliente_ordem_25 VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table importacao_generica alter column campos_cliente_ordem_26 VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table importacao_generica alter column campos_cliente_ordem_27 VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table importacao_generica alter column campos_cliente_ordem_28 VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table importacao_generica alter column campos_cliente_ordem_29 VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table importacao_generica alter column campos_cliente_ordem_30 VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table importacao_generica alter column dado_campo_produto_1_part_1 VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table importacao_generica alter column dado_campo_produto_2_part_1 VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table importacao_generica alter column dado_campo_produto_3_part_1 VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table importacao_generica alter column dado_campo_produto_4_part_1 VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table importacao_generica alter column dado_campo_produto_5_part_1 VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table importacao_generica alter column dado_campo_produto_6_part_1 VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table importacao_generica alter column dado_campo_produto_7_part_1 VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table importacao_generica alter column dado_campo_produto_1_bem_1 VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table importacao_generica alter column dado_campo_produto_2_bem_1 VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table importacao_generica alter column dado_campo_produto_3_bem_1 VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table importacao_generica alter column dado_campo_produto_4_bem_1 VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table importacao_generica alter column dado_campo_produto_5_bem_1 VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table importacao_generica alter column ids_coberturas_participantes_1 VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table importacao_generica alter column ids_coberturas_participantes_2 VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table importacao_generica alter column ids_coberturas_participantes_3 VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table importacao_generica alter column ids_coberturas_participantes_4 VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table importacao_generica alter column ids_coberturas_participantes_5 VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table importacao_generica alter column ids_coberturas_participantes_6 VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table importacao_generica alter column ids_coberturas_participantes_7 VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table importacao_generica alter column ids_coberturas_participantes_8 VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table importacao_generica alter column ids_coberturas_participantes_9 VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table importacao_generica alter column ids_coberturas_participantes_10 VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table importacao_generica alter column ids_coberturas_bem_1 VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table importacao_generica alter column ids_coberturas_bem_2 VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table importacao_generica alter column ids_coberturas_bem_3 VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table importacao_generica alter column ids_coberturas_bem_4 VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table importacao_generica alter column ids_coberturas_bem_5 VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table importacao_generica alter column ids_coberturas_bem_6 VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table importacao_generica alter column ids_coberturas_bem_7 VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table importacao_generica alter column ids_coberturas_bem_8 VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table importacao_generica alter column ids_coberturas_bem_9 VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table importacao_generica alter column ids_coberturas_bem_10 VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table importacao_generica alter column msg_erro VARCHAR (5000) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table protocolo alter column mes_ano CHAR (6) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table itens_segurados alter column nr_proposta VARCHAR (12) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table itens_segurados alter column nr_endosso_prod_emp VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table itens_segurados alter column idioma VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table lancamento_agente alter column idioma VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table lancamento_agente alter column msg_processamento VARCHAR (500) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table lancamento_agente alter column idioma_hierarquia_agente VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table lancamento_agente alter column mes_ano_ref VARCHAR (7) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table beneficiario alter column id_processo VARCHAR (15) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table beneficiario alter column nm_beneficiario VARCHAR (100) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table beneficiario alter column cpf_cnpj_beneficiario VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table beneficiario alter column rg_beneficiario VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table beneficiario alter column nr_tel_beneficiario VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table beneficiario alter column nr_fax_beneficiario VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table beneficiario alter column nr_cel_beneficiario VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table beneficiario alter column email_beneficiario VARCHAR (50) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table beneficiario alter column cep VARCHAR (9) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table beneficiario alter column logradouro VARCHAR (100) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table beneficiario alter column numero VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table beneficiario alter column complemento VARCHAR (50) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table beneficiario alter column nm_responsavel VARCHAR (50) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table beneficiario alter column idioma VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table beneficiario alter column id_beneficiario_legado VARCHAR (100) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table relatorio_produtividade alter column nr_proposta VARCHAR (12) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table relatorio_produtividade alter column nm_fantasia_prod VARCHAR (60) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table relatorio_produtividade alter column cpf VARCHAR (15) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table relatorio_produtividade alter column nm_cliente VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table relatorio_produtividade alter column nm_agente_vendedor VARCHAR (50) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table relatorio_produtividade alter column nm_nivel_01 VARCHAR (50) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table relatorio_produtividade alter column nm_agrupamento_01 VARCHAR (100) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table relatorio_produtividade alter column nm_nivel_02 VARCHAR (50) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table relatorio_produtividade alter column nm_agrupamento_02 VARCHAR (100) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table relatorio_produtividade alter column nm_nivel_03 VARCHAR (50) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table relatorio_produtividade alter column nm_agrupamento_03 VARCHAR (100) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table relatorio_produtividade alter column nm_nivel_04 VARCHAR (50) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table relatorio_produtividade alter column nm_agrupamento_04 VARCHAR (100) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table relatorio_produtividade alter column nm_nivel_05 VARCHAR (50) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table relatorio_produtividade alter column nm_agrupamento_05 VARCHAR (100) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table relatorio_produtividade alter column cd_agente_01 VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table relatorio_produtividade alter column nm_hierarquia_agente_01 VARCHAR (100) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table relatorio_produtividade alter column cd_agente_02 VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table relatorio_produtividade alter column nm_hierarquia_agente_02 VARCHAR (100) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table relatorio_produtividade alter column cd_agente_03 VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table relatorio_produtividade alter column nm_hierarquia_agente_03 VARCHAR (100) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table relatorio_produtividade alter column cd_agente_04 VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table relatorio_produtividade alter column nm_hierarquia_agente_04 VARCHAR (100) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table relatorio_produtividade alter column cd_agente_05 VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table relatorio_produtividade alter column nm_hierarquia_agente_05 VARCHAR (100) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table beneficiarioXprocesso_beneficioXreservaXcobertura_tipo_produto alter column id_processo VARCHAR (15) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table beneficiarioXprocesso_beneficioXreservaXcobertura_tipo_produto alter column idioma VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table resposta_avaliacao_risco alter column id_processo VARCHAR (15) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table beneficiarioXprocesso_beneficioXreservaXsubcobertura_tipo_produto alter column id_processo VARCHAR (15) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table beneficiarioXprocesso_beneficioXreservaXsubcobertura_tipo_produto alter column idioma VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table lancamento_agenteXcotacao_cliente alter column nr_cotacao VARCHAR (12) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table lancamento_agenteXcotacao_cliente alter column idioma_st_pagto VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table lancamento_agenteXcotacao_cliente alter column msg_processamento VARCHAR (500) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table lancamento_agenteXproduto_cliente alter column nr_endosso_prod_emp VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table lancamento_agenteXproduto_cliente alter column nr_proposta VARCHAR (12) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table lancamento_agenteXproduto_cliente alter column idioma_st_pagto VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table lancamento_agenteXproduto_cliente alter column msg_processamento VARCHAR (500) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table rotina_cabecalho_linha alter column idioma VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table rotina_cabecalho_linha alter column nm_campo_layout VARCHAR (100) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table rotina_cabecalho_linha alter column ds_campo VARCHAR (100) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table rotina_cabecalho_linha alter column ds_conteudo VARCHAR (100) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table rotina_cabecalho_linha alter column ds_conteudo_arquivo VARCHAR (1000) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table rotina_cabecalho_linha alter column codigo_tipo_falha VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table rotina_cabecalho_linha alter column ds_erro_arquivo VARCHAR (500) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table lance alter column id_processo VARCHAR (15) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table boleto_franquia alter column id_processo VARCHAR (15) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table boleto_franquia alter column nr_endosso_prod_emp VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table boleto_franquia alter column num_titulo VARCHAR (100) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table boleto_franquia alter column nosso_num VARCHAR (100) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table boleto_franquia alter column linha_dig VARCHAR (100) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table boleto_franquia alter column num_doc VARCHAR (100) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table boleto_franquia alter column idioma_mot_cancel VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table boleto_franquia alter column idioma_st_titulo VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table boleto_franquia alter column cod_banco VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table boleto_franquia alter column instrucao VARCHAR (500) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table rotina_registro_linha alter column nm_campo_layout VARCHAR (100) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table rotina_registro_linha alter column ds_campo VARCHAR (100) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table rotina_registro_linha alter column ds_conteudo VARCHAR (100) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table rotina_registro_linha alter column idioma VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table rotina_registro_linha alter column idioma_cobertura_tipo_produto VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table rotina_registro_linha alter column idioma_subcobertura_tipo_produto VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table rotina_registro_linha alter column idioma_produtoXbem VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table rotina_registro_linha alter column idioma_produtoXtipo_participante VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table rotina_registro_linha alter column idioma_prod_campos_beneficiario VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table rotina_registro_linha alter column idioma_sinistro VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table rotina_registro_linha alter column ds_conteudo_arquivo VARCHAR (1000) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table rotina_registro_linha alter column codigo_tipo_falha VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table rotina_registro_linha alter column ds_erro_arquivo VARCHAR (500) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table lista_negra alter column id_fluxo VARCHAR (50) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table lista_negra alter column nome VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table lista_negra alter column primeiro_nome VARCHAR (100) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table lista_negra alter column segundo_nome VARCHAR (100) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table lista_negra alter column nro_documento VARCHAR (100) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table lista_negra alter column placa VARCHAR (25) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table lista_negra alter column motor VARCHAR (50) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table lista_negra alter column chasis VARCHAR (100) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table lista_negra alter column ds_delito VARCHAR (5000) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table lista_negra alter column dt_delito VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table lista_negra alter column situacao_atual VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table lista_negra alter column novidade VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table campanhaXmailing alter column nr_endosso_prod_emp VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table campanhaXmailing alter column nr_cotacao VARCHAR (12) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table campanhaXmailing alter column idioma_status_prospect_camp VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table campanhaXmailing alter column idioma_motivo_recusa VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table campanhaXmailing alter column idioma VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table local_atendimento alter column id_processo VARCHAR (15) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table local_atendimento alter column cep VARCHAR (9) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table local_atendimento alter column logradouro VARCHAR (100) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table local_atendimento alter column numero VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table local_atendimento alter column complemento VARCHAR (50) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table local_atendimento alter column ponto_referencia VARCHAR (50) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table local_atendimento alter column telefone VARCHAR (14) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table local_atendimento alter column nm_profissional VARCHAR (40) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table local_atendimento alter column no_profissional VARCHAR (7) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table local_atendimento alter column idioma_tp_local VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table local_atendimento alter column bairro VARCHAR (100) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table cliente alter column vl_chave1_cli VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table cliente alter column vl_chave2_cli VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table cliente alter column vl_chave3_cli VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table cliente alter column idioma_chave1 VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table cliente alter column idioma_chave2 VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table cliente alter column idioma_chave3 VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table cliente alter column id_cli_legado VARCHAR (100) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table log_analitico alter column vl_chave1_cli VARCHAR (100) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table log_analitico alter column vl_chave2_cli VARCHAR (100) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table log_analitico alter column vl_chave3_cli VARCHAR (100) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table log_analitico alter column nome_endereco_arquivo VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table log_analitico alter column linha_arquivo VARCHAR (Max) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table log_analitico alter column cod_erro VARCHAR (100) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table log_analitico alter column desc_erro VARCHAR (Max) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table log_analitico alter column idioma VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table selecao_cobranca alter column nr_proposta VARCHAR (12) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table selecao_cobranca alter column mes_ano_ref VARCHAR (10) collate  SQL_Latin1_General_CP1_CI_AS not  null;
alter table selecao_cobranca alter column ds_erro VARCHAR (Max) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table selecao_cobranca alter column obj_envio VARCHAR (Max) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table selecao_cobranca alter column obj_retorno VARCHAR (Max) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table selecao_cobranca alter column cd_autorizacao VARCHAR (20) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table cliente_dados_meio_pagto alter column valor_dado VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table log_do_log alter column erro VARCHAR (500) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table log_do_log alter column nm_tabela VARCHAR (255) collate  SQL_Latin1_General_CP1_CI_AS null;
alter table log_do_log alter column nm_campo VARCHAR (8000) collate  SQL_Latin1_General_CP1_CI_AS null;
rollback